name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  ci-pizza-planet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to my branch
        uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report -m